version: "3.7"

services:
  nodejs:
    image: node:16
    command: "bash -c 'cd /usr/src/app && npm start'"
    ports:
      - 3000:3000
    volumes:
      - '.:/usr/src/app'
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - type: bind
        source: ./api/dist
        target: /swagger

